name: 'Create an Immutable Release'
description: 'Create an immutable release for a tag on the IOTA Tangle'
author: 'IOTA Foundation'
inputs:
  tag_name:
    description: 'The name of the tag. This should come from the webhook payload, `github.GITHUB_REF` when a user pushes a new tag'
    required: true
  comment:
    description: 'An optional comment to include in the Tangle payload'
    required: false
outputs:
  tx_hash:
    description: 'The hash of the transaction on the Tangle'
  tx_explore_url:
    description: 'A url which can be used to explore the transaction on the Tangle'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
